name: "matts_mtg"

config-version: 2
version: "0.1"

profile: "matts_mtg"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  dbt_project:
    staging:
      +materialized: view
      +schema: main
    sub_sets:
      +materialized: table
      +schema: main
